namenode:
  host: "ec2-3-92-73-140.compute-1.amazonaws.com"
  port: 50051

datanodes:
  - host: "ec2-44-212-74-74.compute-1.amazonaws.com"
    port: 50052
  - host: "ec2-54-165-217-87.compute-1.amazonaws.com"
    port: 50052