namenode:
  host: "ec2-3-92-73-140.compute-1.amazonaws.com "
  port: 50051

datanodes:
  - host: "ec2-18-234-94-209.compute-1.amazonaws.com"
    port: 50052
  - host: "ec2-54-145-178-98.compute-1.amazonaws.com"
    port: 50052